// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnccezzqcohvgzkwojqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuY2NlenpxY29odmd6a3dvanF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzUzODgsImV4cCI6MjA2OTc1MTM4OH0.UBO5OGUOJaOnbWgsuWX6yxBum2jRk9jOPfHt-ALGnkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});